version: '3.5'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  influxdb:
    image: influxdb:1.7
    restart: always
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=interactws-admin
      - INFLUXDB_ADMIN_PASSWORD=interactws-admin
      - INFLUXDB_DB=interactws
      - INFLUXDB_USER=interactws
      - INFLUXDB_PASSWORD=interactws
      - INFLUXDB_HTTP_AUTH_ENABLED=true

  schema-registry:
    image: confluentinc/cp-schema-registry:5.3.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
        - zookeeper
        - kafka
    ports:
        - "8081:8081"
    environment:
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'

  kafka2influxdb:
    image: labbsr0x/kafka2influxdb
    build: .
    restart: always
    depends_on:
      - zookeeper
      - kafka
      - influxdb
      - schema-registry
    ports:
      - 8000:8000
    environment: 
      - KFK2INF_PORT=8000
      - KFK2INF_KAFKA_ADDR=kafka:29092
      - KFK2INF_KAFKA_TOPIC=owner
      - KFK2INF_KAFKA_SCHEMA_REGISTRY=schema-registry:8081
      - KFK2INF_INFLUXDB_ADDR=http://influxdb:8086
      - KFK2INF_INFLUXDB_NAME=interactws
      - KFK2INF_INFLUXDB_USER=interactws-admin
      - KFK2INF_INFLUXDB_PASSWORD=interactws-admin
      - KFK2INF_WITH_SASL=false

  local:
    image: busybox
    depends_on:
      - zookeeper
      - kafka
      - influxdb
      - kafka2influxdb