name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Mushus/golangci-linter@v1
    - name: Lint
    - uses: actions/checkout@master
    - name: Publish to Docker Repository
      uses: labbsr0x/kafka2influxdb@master
      with:
          name: gabrieldossantos/kafka2influxdb
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
